# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 14 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "nasa-cdf" %}
{% set version = "3.7.1" %}
{% set dist_version = "37_1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://spdf.gsfc.nasa.gov/pub/software/cdf/dist/cdf{{ dist_version }}/cdf-dist-all.tar.gz
  sha256: bbc8f9295e732173eb4b8c1eb2e7e6c045ae0934573ee451fe8ead1c5eee61bb

build:
  number: 0


requirements:
  build:
    - {{ compiler('c') }}
    - make  # [not win]
    - cmake  # [win]
  host:
  run:

test:
  commands:
    - test -f $PREFIX/lib/libcdf$SHLIB_EXT  # [unix]
    - cdfstats -about  # [unix]
    - cdfstats.exe -about  # [win]

about:
  home: https://cdf.gsfc.nasa.gov/
  license: CDF Copyright
  license_file: CDF_copyright.txt
  summary: 'NASA CDF software distribution to read and write Common Data Format files.'

  description: |
    CDF is the Common Data Format.  It is a conceptual data abstraction for
    storing, manipulating, and accessing multidimensional data sets.  The basic
    component of CDF is a software programming interface that is a device-
    independent view of the CDF data model.  The application developer is
    insulated from the actual physical file format for reasons of conceptual
    simplicity, device independence, and future expandability.  CDF files
    created on any given platform can be transported to any other platform onto
    which CDF is ported and used with any CDF tools or layered applications.
    The CDF software, documentation, and user support services are provided
    by NASA and available to the public free of charge. There are no license
    agreements or costs involved in obtaining or using CDF.
  doc_url: https://cdf.gsfc.nasa.gov/html/cdf_docs.html

extra:
  recipe-maintainers:
    - AntoineBrunet
